# Basket option implementation based on normal model

In [1]:
import numpy as np
from option_models import basket
from option_models import bsm
from option_models import normal

In [30]:
### only run this when you changed the class definition
import imp
imp.reload(basket)

<module 'option_models.basket' from 'C:\\Users\\rapha\\OneDrive\\Documents\\GitHub\\PHBS_ASP_2018\\HW3\\option_models\\basket.py'>

In [3]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

print(weights)

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

[1 0 0 0]


In [4]:
# Compare the price to normal model formula

norm1 = normal.NormalModel(40)
price_norm = norm1.price(strike=120, spot=100, texp=texp, cp_sign=1)
print(price_basket, price_norm)

26.763909734339606 26.570845957870503


In [5]:
# A trivial test case 2

# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
print(price_basket, price_norm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
26.761395615904505 26.570845957870503


In [21]:
# A test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)
price_exact = 28.0073695

print(price_basket, price_exact)

28.168716545630815 28.0073695


# [To Do] Basket option implementation based on BSM model
## Write the similar test

In [6]:
price_basket = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, bsm=False)

In [7]:
# A trivial test case 1: 
# one asset have 100% weight (the others zero)
# the case should be equivalent to the BSM or Normal model price (we do it using either bsm=True or bsm=False)

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket)

28.751631082489702


In [9]:
# Compare the price to BSM model formula

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.array([1, 0, 0, 0])
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 120

price_bsm = bsm.bsm_price(strike, spot[0], vol[0], texp, intr, divr[0], cp_sign=1)
print(price_basket, price_bsm)

28.751631082489702 28.713486748445934


In [4]:
# A trivial test case 2

# all assets almost perfectly correlated:
# the case should be equivalent to the BSM or Normal model price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.0001*np.identity(4) + 0.9999*np.ones((4,4))
texp = 5
strike = 120

print( cor_m )

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(price_basket, price_bsm)

[[1.     0.9999 0.9999 0.9999]
 [0.9999 1.     0.9999 0.9999]
 [0.9999 0.9999 1.     0.9999]
 [0.9999 0.9999 0.9999 1.    ]]
28.738539105928172 28.713486748445934


In [22]:
# A test set for basket option with exact price

spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

np.random.seed(123456)
price_basket = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
price_exact = 28.0073695

print(price_basket, price_exact)

27.566752423198636 28.0073695


# Spread option implementation based on normal model

In [77]:
# A test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
price_exact = 8.5132252

In [78]:
# MC price based on normal model
# make sure that the prices are similar\

np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)
print(price_spread, price_exact)

8.348852807225292 8.5132252


# Spread option implementation based on BSM model

In [12]:
# A test set for spread option

spot = np.array([100, 96])
vol = np.array([0.2, 0.1])
weights = np.array([1, -1])
divr = np.array([1, 1])*0.05
intr = 0.1
cor_m = np.array([[1, 0.5], [0.5, 1]])
texp = 1
strike = 0
np.random.seed(123456)

# Kirk's approximation

price_kirk = basket.spread_price_kirk(strike, spot, vol, texp, 0.5, intr, divr)
np.random.seed(123456)
price_spread = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, intr=intr, divr=divr, bsm=True)
print(price_spread, price_kirk)

8.109605793968353 8.5132252295455


# [To Do] Complete the implementation of basket_price_norm_analytic
# Compare the MC std of BSM basket prices from with and without CV

In [80]:
# the price from basket.basket_price_norm_analytic should be also similar
# basket.basket_price_norm_analytic(strike, spot, vol*spot, weights, texp, cor_m, intr=intr, divr=divr, bsm=False)

In [2]:
# using the same values as "A test set for basket option with exact price"
spot = np.ones(4) * 100
vol = np.ones(4) * 0.4
weights = np.ones(4) * 0.25
divr = np.zeros(4)
intr = 0
cor_m = 0.5*np.identity(4) + 0.5
texp = 5
strike = 100

In [4]:
#BSM without CV
np.random.seed(123456)
BSM_noCV = basket.basket_price_mc(strike, spot, vol, weights, texp, cor_m, bsm=True)
print(BSM_noCV)

27.566752423198636


In [5]:
### Make sure that the analytic normal price is correctly implemented
normanalytic = basket.basket_price_norm_analytic(
    strike, spot, vol*spot, weights, 
    texp, cor_m, intr=0.0, divr=0.0, cp_sign=1)
print(normanalytic)

28.209479177387816


In [3]:
# Run below about 100 times and get the mean and stdev
### Returns 2 prices, without CV and with CV 
values = [basket.basket_price_mc_cv(strike, spot, vol, weights, texp, cor_m,
intr=0.0, divr=0.0, cp_sign=1, n_samples=10000) for k in range(100)]
stack_values = np.stack(values)

In [4]:
 print("mean without CV =", np.mean(stack_values[:,0])," standard deviation without CV =", np.std(stack_values[:,0])),print("mean with CV =", np.mean(stack_values[:,1])," standard deviation with CV =", np.std(stack_values[:,1]))

mean without CV = 27.998573360767892  standard deviation without CV = 0.6557142893390048
mean with CV = 28.035198302534432  standard deviation with CV = 0.3660388362187842


(None, None)

The standard deviation with the control variance technique is lower based on 100 simulations